### ISSUE TITLE
Add option to omit domain name from email address usernames

### ISSUE THREAD

**Issue by seesemichaelj** [SRombauts/UE4PlasticPlugin#100]
This is related to #99 in that it provides another option for displaying less text for email-based usernames for Plastic Cloud repos. I believe that having both #99 and this feature would be beneficial, where this feature could be the MVP.

This option would attempt to omit the email domain name if the username is an email address (i.e. `sleepypanda@gmail.com` becomes `sleepypanda`).

**Comment by SRombauts** [comment]
Yes, I totally agree, thanks for both of your suggestions!
This one could even be enabled by default I believe, as most often the domain part of the email addresses is meaningless; either always the same for everyone in the organization, or the reverse, very diverse/chaotic but not relevant

**Comment by seesemichaelj** [comment]
Fixed in #101
