### ISSUE TITLE
Script Folder ignore?

### ISSUE THREAD

**Issue by RoadkilladilloStudio** [SRombauts/UE4PlasticPlugin#110]
Okay so I am not completely sure what the Script folder in UE5 is for. But I just switched to Plastic SCM and noticed the SCRIPT folder that is always empty keeps getting flagged for pending commits with Plastic SCM.

I am not sure if I should or shouldn't ignore this folder. Not much documentation on UE side as to what its exactly for. Watching the commits, I am guessing with the JS files and typing files its just writing plugin related stuff like a cache but I really could use an official what it is maybe from the team here.

Reason I am posting an issue though, last night I decided to add it to the ignore list. Just to see how things work without me managing it. Oddly, the ignore on the Script folder didn't take. I see it on the ignore file but every time I reboot UE5 its kicking random pending commits and unsure if I should watch this folder and commit or find another route to ignore it. Oddly though every time it asks for commits its always on load of the engine. Go into the folder though its always empty so I am unsure here what Plastic SCM is calling for and why its constantly spamming on this.

Any ideas what might be the use in this folder. If I should find another way to ignore or is this something I should always add to my daily commits?

**Comment by SRombautsU** [comment]
Hi,

I have seen this on UE5.0 from the launcher, but not recently when working on upcoming EU5.1 from sources
I have no idea why it appeared, nor what it would be used to, but I think it's not anymore in 5.1 source code; I cannot find anything relevant, except that all Blueprints, are referred as /Script/

I have always added to ignore.conf without any more issue, and I think it's safe to do that

Cheers!
Sébastien

**Comment by SRombautsU** [comment]
I have explicitly added the Script/ folder to the ignore.conf default template, even though I am not sure it will be useful for UE5.1
