### ISSUE TITLE
Unable to package with the plugin enabled

### ISSUE THREAD

**Issue by Ryounoshi** [SRombauts/UE4PlasticPlugin#2]
Package a game for windows result in a fail if the Plastic Plug-In is enabled.

Here is the error comming from the packaging log

UATHelper: Packaging (Windows (64-bit)): UE4Editor-Cmd: [2016.11.09-10.11.35:762][  0]LogWindows:Error: Assertion failed: (!ModuleInfo->bWasUnloadedAtShutdown) [File:D:\Programs\UnrealEngine\UnrealEngine4_13\Engine\Source\Runtime\Core\Private\Modules\ModuleManager.cpp] [Line: 373] 
UATHelper: Packaging (Windows (64-bit)): UE4Editor-Cmd: [2016.11.09-10.11.35:762][  0]LogWindows:Error: Attempted to load module 'LevelEditor' that was already unloaded at shutdown.  FModuleManager::LoadModule() was called to load a module that was previously loaded, and was unloaded at shutdown time.  If this assert goes off, your trying to load a module du

**Comment by SRombauts** [comment]
Hi @Ryounoshi, thanks for reporting this, I will look into this in the comming days if I can. 

Can you give me some more information please ? 
1. From what I see it seems to me that you are using UE4.13, are you building the Engine from sources (ie.  from GitHub) ?
2. Where did you put the Plastic SCM plugin ? In your project Plugins directory ? In the Engine directory ?
3. Is this à C++ project or à "Content only" project (ie Blueprints only) ? 
4. Are you using à binary release of the plugin, or rebuilding from sources ?

If you can answer all this it could help reproduce quicker. Either way, I should probably try every variants to be sure. 

Best Regards

**Comment by Ryounoshi** [comment]
Hello,

1) We use an Unreal Engine built from source (4.13)
2) I tried both way, the result is the same
3) The project is a C++ project
4) I rebuilt the plugin from sources (version 0.9.1)

Thanks for the answer.

Cheers

**Comment by SRombauts** [comment]
Thanks for the update !

**Comment by SRombauts** [comment]
I reproduced the problem, and quickly discovered that it is a regression from 0.8.1: somehow, the extension of the Source Control menu is causing a dependency problem of some sort.
I'll try to track this own further.
Cheers!

**Comment by SRombauts** [comment]
Hi @Ryounoshi, can you please confirm that the provided fix in 0.9.2 actually solve your issue?
At least it works for me.
Cheers!

**Comment by Ryounoshi** [comment]
Hi @SRombauts, everything is working fine now. 
Thanks for the fix !
Cheers.
