### ISSUE TITLE
Gluon checkins are not showing the changeset created

### ISSUE THREAD

**Issue by mrcatacroquer** [SRombauts/UE4PlasticPlugin#24]
While working with a Gluon workspace if you try to checkin a set of changes you'll see how after the "The selected items are about to be checked in. Please wait..." message there's nothing after it.

It would be nice a checkin confirmation in order to know the checkin operation took place.

**Comment by SRombauts** [comment]
Presently, the popup simply displays the last line of output from 'cm', which is working nicely for normal workspaces.

When in partial/Gluon mode, this is what I get from the command line:

```C:\xxx\UE4PlasticPluginDev>cm partial checkin Content\UE4PlasticPluginDev\Blueprints\Actor_BP.uasset
The selected items are about to be checked in. Please wait ...
```

From the plugin point of view, the checkin is finished and successful, but the 'cm' cli is not giving us the expected output.

So should I switch to display a status info (from the 'cm status' command executed just after) ?

**Comment by mrcatacroquer** [comment]
That's a good one! I wasn't aware the ci was not telling us the changeset created.

In that case I think you can just notify a "Checking finished correctly" or something similar when the ci command returns.

**Comment by SRombauts** [comment]
So I kept the best of each world:
1. in normal workspace, the last line starts with a "Created changeset" and is displayed as-is, as before
2. in partial/gluon mode, the popup now says "Changeset submitted successfully."

**Comment by mrcatacroquer** [comment]
Great! :)
