### ISSUE TITLE
Request: Plastic mirror

### ISSUE THREAD

**Issue by M-Pixel** [SRombauts/UE4PlasticPlugin#37]
It would be great if I could xlink this plugin into my project. I suspect that this Git repository is probably a mirror of a Plastic repo. Either way, could a Plastic repo of this plugin be hosted for public read-only access?

**Comment by SRombauts** [comment]
Seems like a good idea to me. I am not aware of any server where I could host an open source Plastic SCM repository.  Do you?

Else I will ask the Plastic SCM team.

**Comment by M-Pixel** [comment]
I'm not aware of any. Definitely run the idea by others at Codice - it advertises a cool feature and simplifies the installation instructions.

**Comment by gkoreman** [comment]
I am git-syncing this repo into my plastic server and then xlinking from there. Seems to work alright. I do this with a number of open source projects that we use and it's great that they all come from a widely supported highly available service like Git. I wouldn't recommend changing hosting providers.

**Comment by M-Pixel** [comment]
I wouldn't recommend _changing_ providers either.

@gkoreman I'm doing the same as you. It would be nice if I didn't have to. Also, there's always the danger that if @SRombauts ever pushes a fast-forward-merge to GitHub, then Git Sync will cease to work. If Codice hosts their own sync of this repo, then it advertises Plastic Cloud XLinking, and simplifies the installation instructions.

**Comment by SRombauts** [comment]
won't happen soon imo
