### ISSUE TITLE
Binaries for PlasticSourceControl plugin are missing or incompatible with 4.18.1

### ISSUE THREAD

**Issue by visualcodex** [SRombauts/UE4PlasticPlugin#38]
Using both default UE4PlasticPlugin-1.0.5 and Epic engine 4.18.1 
Tried both on existing Unreal 4.18 and a freshly created project. Every time I unzip and copy paste the PlasticPlugin in my case: "C:\Temp\New18\Plugins\UE4PlasticPlugin"
I think I got everything right. But to no avail I get the following error message. And regardless if I choose yes or no, then try to activate the plugin after I started the editor and restart, etc 
![image](https://user-images.githubusercontent.com/18391857/32898852-3e681c0c-cae1-11e7-98d4-e25e5849e50e.png)
and
![image](https://user-images.githubusercontent.com/18391857/32899038-bc1f7b5e-cae1-11e7-96f1-ff39976be42b.png)

I do have it working in all previous engines. Just can't get it to work with 4.18 and don't know why. It prevents me from properly updating a current cloud shared project to 4.18
Any help most appreciated.

**Comment by SRombauts** [comment]
I'll try this myself asap, but the usual suspect is that you did not download the zip with Binaries in it.

**Comment by SRombauts** [comment]
Ah ah, more interesting, it seems that the build for the 4.18 is not compatible with the new 4.18.1! First time this happens... I'll do a new release asap!

**Comment by visualcodex** [comment]
I did actually go through the effort of cross checking the directories and binaries from my working Plugins in 4.17 against the 4.18.  To make double sure I had most critical binaries. But I just saw you where able to reproduce it. Thanks for looking into this!
Kind Regards.

**Comment by SRombauts** [comment]
Well, I think I've found the culprit: a missing file in the release!
The missing file seems to be a new dependency for 4.18, no reason it would have appeared on 4.18.1 (but no way for me to go back to 4.18 to check).

Can you let me know if it is working also for you?

Working on the release!

**Comment by SRombauts** [comment]
Also, I am very sorry for the inconvenience, I regret I didn't see the issue by myself before!

The problem is a often always use in-development version, so I may miss problem of a release if I let it go through in the first place.

**Comment by visualcodex** [comment]
Works like a charm Mister Rombauts, just tried it. All good! Thank you very much!

**Comment by SRombauts** [comment]
You're welcome!
