### ISSUE TITLE
Rename in UE4 causes locking

### ISSUE THREAD

**Issue by gkoreman** [SRombauts/UE4PlasticPlugin#39]
If you rename a file in UE4 the new file appears to be locked by someone else (shows up with a blue checkmark). This is inconvenient as this means that if a file is renamed it cannot be moved as well in the same checkin. In the Plastic UI the file correctly shows that you have a lock on it, and the checkin works fine.

Ideally you can move, rename, and clean up redirectors all in the same checkin.

**Comment by SRombauts** [comment]
Obviously, it is meant to work as you expect, and it surely did in the past.
I will have to take some time to look into this.

**Comment by gkoreman** [comment]
Thanks for looking into this. Let me know if you need any more information from our end. We're looking forward to having this fixed.
