### ISSUE TITLE
Plugin can create an ignore.conf file in the wrong place

### ISSUE THREAD

**Issue by Ecnassianer** [SRombauts/UE4PlasticPlugin#47]
I used the plugin to create my ignore.conf. It created it next to my uproject (the version with "x" next to it in the image). Then I added my project in Gluon. The ignore.conf had no effect. I created a new ignore.conf in the root level of my workspace (with the check mark in the image) and that ignore.conf file works.

![image](https://user-images.githubusercontent.com/231247/35774914-fbc729f8-0931-11e8-92a8-e3afc45070e2.png)

Is the plugin putting the ignore.conf in the wrong place in this case?

**Comment by SRombauts** [comment]
Hi, Thanks for reporting this!

I'll have to check this, but I assume that you are right that the ignore file should be created at the root of the workspace, with appropriate content

**Comment by reveracorp** [comment]
Hi, I just came across same issue as well. Not sure this one has been addressed.

**Comment by SRombauts** [comment]
True, thanks for pointing this out, it's a shape that Plastic SCM doesn't deal with ignore file in subfolders like Perforce or Git

I'll see if I can detect this case and adapt the ignore file for this usage.

**Comment by SRombauts** [comment]
Fixed by 61fc27c
