### ISSUE TITLE
Whitespaces in Repo name causing errors

### ISSUE THREAD

**Issue by rfruesmer** [SRombauts/UE4PlasticPlugin#48]
Hi, 

i am new to Plastic SCM so idk if this a real defect or if i have misunderstood something.

When using a Plastic SCM repo named like "MyProject 1.0" for example, the plugins diff tool or history viewer don't work anymore. After Changing the repo name to "MyProject" those plugin features work as expected in UE4 Editor.

Aren't whitespace characters and/or version numbers supported in repo names for the plugin or is it some limitation of the source control provider? 

Please advise.

Best Regards,
Reinhold

**Comment by SRombauts** [comment]
Hi, thanks for reporting this, it is most probably a bug in my code, I'll have a look.

Is this urgent/important to you?

**Comment by rfruesmer** [comment]
Hi,

no its not urgent for our team anymore since we renamed the repo and its working fine for us now.

But it would be good when other teams are kept from running into this trap in future - it took us some time to figure it out.

Big thanks for providing this plugin to the community!!

**Comment by SRombauts** [comment]
Fixed by #79 Delimit rev-spec in RunDumpToFile
