### ISSUE TITLE
Renaming files is very slow with a large repository

### ISSUE THREAD

**Issue by gkoreman** [SRombauts/UE4PlasticPlugin#49]
We have a large (and rapidly growing) repository using UE4. Renaming a file takes quite a long time.

I looked into it a little bit and it turns out that a FPlasticConnectWorker gets run before a file is renamed and the connect operation runs a (very slow) RunUpdateStatus on the ProjectContentDir().

Does FPlasticConnectWorker need to be run when renaming files? 
Does FPlasticConnectWorker need to do a RunUpdateStatus on the entire depot on launch?
Is there another way to speed up source control operations when working on large projects?

**Comment by SRombauts** [comment]
No, Connect should never occurs more than once, it might be triggered by a previous error... can you see anything in the logs?

Connect is indeed triggering a full status operation, but it was intended as a one time asynchronous event in background of the project loading.
It would be easy to add a security to avoid doing it twice. I could also make it optional, even though I find it very useful in times, and missing from the Perforce plugin IMO.

Could you perhaps make a minimal scenario (Start the Editor, Rename à file) and post or send me privately the logs?
I will not have access to my computer before tomorrow I think

**Comment by gkoreman** [comment]
Hi Sebastien,
Have you had a chance to look at the connect trigger? I took a brief look at our logs and didn't see any source control errors. I would prefer not to send logs unless absolutely necessary.

**Comment by gkoreman** [comment]
Hi Sebastien,
This issue is still occurring. Is there a way for us to provide you with a log that doesn't include sensitive information? I can outline the order calls are being made if that helps.

**Comment by gkoreman** [comment]
To add a bit more information to this ticket:

Connect gets called from the LevelEditorToolbar when UE4 starts. This call is asynchronous and will refresh everything.

Connect also gets called inside ISourceControlProvider::Login, which gets called with this callstack:

>	UE4Editor-PlasticSourceControl.dll!ISourceControlProvider::Login(const FString & InPassword, EConcurrency::Type InConcurrency, const TBaseDelegate<void,TSharedRef<ISourceControlOperation,1> const &,enum ECommandResult::Type> & InOperationCompleteDelegate) Line 122	C++
 	UE4Editor-AssetTools.dll!FAssetRenameManager::UpdatePackageStatus(const TArray<FAssetRenameDataWithReferencers,FDefaultAllocator> & AssetsToRename) Line 483	C++
 	UE4Editor-AssetTools.dll!FAssetRenameManager::FixReferencesAndRename(const TArray<FAssetRenameData,FDefaultAllocator> & AssetsAndNames, bool bAutoCheckout, bool bWithDialog) Line 296	C++
 	UE4Editor-AssetTools.dll!FAssetRenameManager::RenameAssetsWithDialog(const TArray<FAssetRenameData,FDefaultAllocator> & AssetsAndNames, bool bAutoCheckout) Line 234	C++
 	UE4Editor-ContentBrowser.dll!ContentBrowserUtils::RenameAsset(UObject * Asset, const FString & NewName, FText & ErrorMessage) Line 467	C++
 	UE4Editor-ContentBrowser.dll!SAssetView::AssetRenameCommit(const TSharedPtr<FAssetViewItem,0> & Item, const FString & NewName, const FSlateRect & MessageAnchor, const ETextCommit::Type CommitType) Line 4075	C++



I made a change to FPlasticConnectWorker::Execute to see if we have ever updated our status and if we have, skip the RunUpdateStatus command. Works well for us. Do you see any issues with this approach?

**Comment by SRombauts** [comment]
Hi, I am sorry I didn't even took the time to answer you: I ended up with my mailbox full of unanswered issues, while I was starting a new job at a startup company!

What you did seems nice to me, could you make a merge request? I'll give it a try asap (don't want to make too many promesse but would love to catch up on open source work) 

Please,

**Comment by SRombauts** [comment]
I am working on this right now, I have immediately reproduced the issue thanks to your recent comment, and I'll try to see if I can avoid the Editor firing a new synchronous Connect operation, since this is the root of the issue

**Comment by gkoreman** [comment]
Hi Sebastien, congratulations on the new job. Thanks for taking a look at this, it sounds like your fix gets at the root cause.
Cheers,
Greg
