### ISSUE TITLE
Feature Request:  Complain when user attempts to work on out-of-date file

### ISSUE THREAD

**Issue by M-Pixel** [SRombauts/UE4PlasticPlugin#52]
[Plastic's exclusive-checkout design is fundamentally broken](https://plasticscm.uservoice.com/forums/15467-general/suggestions/5777349-workspace-wide-exclusive-checkout) in a way that particularly affects UE4 projects.  It would be great if this plugin made up for the deficiency by creating some sort of alert when the user attempts to modify a uasset that is not the newest version of that file.

**Comment by SRombauts** [comment]
Well, I am not sure to understand; the Editor is already complaining when you are trying to checkout a file for which there is a newer version on the server on the same branch.
If it is a new revision on another branch, the plugin does not have this info and cannot do anything.

**Comment by M-Pixel** [comment]
> on the same branch
You got it, this is the part that is problematic.

> If it is a new revision on another branch, the plugin does not have this info and cannot do anything.
`cm history Game\Content\Asset.uasset` is one way of determining if there is a newer version of some asset on a different branch, and the plugin gets its info using `cm` commands, so I don't believe that this is an impossible feature.
