### ISSUE TITLE
New-style status command from 8.0.16.3000 crashes the plugin

### ISSUE THREAD

**Issue by moppius** [SRombauts/UE4PlasticPlugin#58]
The PlasticSCM release for 8.0.16.3000 ([release notes here](https://www.plasticscm.com/download/releasenotes/oldernotes?release=8.0.16.3000)) introduces a new-style format for the output from the `cm status` command.

This causes the `RunStatus` method to fail and crash due to the unexpected output when the UE4PlasticPlugin is used with version 8.0.16.3000 or newer.

**Comment by moppius** [comment]
We have a WIP hotfix branch here: https://github.com/EmbarkStudios/UE4PlasticPlugin/tree/hotfix/legacy-status-format - I will open a PR once we have validated everything is working (currently it no longer crashes, but checking out seems broken).

**Comment by SRombauts** [comment]
Hi @moppius, thanks again for you original fix.

I made a new release https://github.com/SRombauts/UE4PlasticPlugin/releases/tag/1.4.5 to fix some additional bugs that where indeed still present in 1.4.3:
https://github.com/SRombauts/UE4PlasticPlugin/releases/tag/1.4.5

I remember you told me you are not using it anymore, but might be useful to be aware of this anyway.

It was also nice to meet you briefly at Unreal Fest Europe :)
