### ISSUE TITLE
Might not work with Plastic SCM 8.0.16

### ISSUE THREAD

**Issue by reveracorp** [SRombauts/UE4PlasticPlugin#61]
Automatic checkout does not seem to be working correctly with Plastic 8.

The plugin is acting as if it is already checked out by another user. However my user IS that other user. 😺

**Comment by reveracorp** [comment]
![image](https://user-images.githubusercontent.com/23106163/54064046-ead6c680-41de-11e9-91c4-cfe370998806.png)

**Comment by SRombauts** [comment]
Hi, thanks for reporting!

Are you using the latest release from last week? It was working nicely on my machine.

Could you share your logs please?

**Comment by reveracorp** [comment]
Upgrading to latest fixed it! (I thought I had but had forgotten to clear Intermediate and Binary)

https://pastebin.com/8bf6dvsq

Log linked above incase you were curious anyway. :) Thank you so much! We make great use of the plugin. It is so useful!

**Comment by SRombauts** [comment]
Hey @reveracorp, I made a new release https://github.com/SRombauts/UE4PlasticPlugin/releases/tag/1.4.5 to fix some additional bugs that where **indeed** still present in 1.4.3!
https://github.com/SRombauts/UE4PlasticPlugin/releases/tag/1.4.5
