### ISSUE TITLE
Missing checkouts for large projects

### ISSUE THREAD

**Issue by knapsu** [SRombauts/UE4PlasticPlugin#65]
Plugin version: `1.4.5`
Unreal version: `4.20`, `4.21`, `4.22`

When starting the Editor with Plastic SCM source control enabled, it checks *every* file in the project. This for projects with very large amount of files takes about a minute. On machines without SSD it takes even longer. During that time users can modify and overwrite files without checking them out from Plastic. This does not happen with small projects where check is fast.

This causes problems as if asset files are not exclusively checked-out (locked) we had several cases of unmergeable files being edited by two people at the same time. Also on the checking dialog these files are not even visible which results in incomplete checkins (not having all modified files) and a broken build on CI.

Problem lies in `PlasticSourceControlOperations.cpp` line 75 to 81.
https://github.com/SRombauts/UE4PlasticPlugin/blob/aaa4998001c2173f03ddd95aedb9d161186fed2b/Source/PlasticSourceControl/Private/PlasticSourceControlOperations.cpp#L75-L81

The Connect command which is done async doesn't finish until *all* the content files are checked. While that is happening in the background, the whole version control is not enabled, allowing the user to do whatever he/she wants.

After commenting out those lines everything seems to work and without the heavy and long check. I am uncertain why this check is done here, that is why @SRombauts your opinion is needed.

**Comment by knapsu** [comment]
If the workspace is inspected from within Plastic GUI or Gluon we can see correctly all the locally changed files but from within Unreal Editor those "edited quickly" are not shown.

**Comment by SRombauts** [comment]
Okay, so 1) this should become an optional feature.
This was requested to avoid having unknown status of files in subfolders; you end up with strange context menu if the content is in unknown status.

The plugin should be able to display locally modified files, but I guess it's half broken when the change happen while the async status operation is running... 

Regards

**Comment by SRombauts** [comment]
Hi @knapsu, I added a setting for this, it default to not updating status at editor startup.

Let me know how it goes for you

**Comment by SRombauts** [comment]
For anyone else digging in old issues like myself, I have now optimized a lot the global Update Status so it should be working just fine for any project size.
