### ISSUE TITLE
Opening project through Epic's launcher make the plugin unfuctionnal

### ISSUE THREAD

**Issue by Cypaubr** [SRombauts/UE4PlasticPlugin#66]
When we lauch our project from the Epic Games laucher, the plugin can not be used because it can't find the cm executable.
Launching the project directly from UE4 (or the file explorer) makes the plugin works fine.

**Comment by SRombauts** [comment]
Oh, that's a very interesting report, and would explain why some people need the full path to the executable.

I guess that it could be related to the environment that is passed from the launcher to the editor...

So I think that the best option would be to change the plugin to now default to a full path.

**Comment by SRombauts** [comment]
Also, I am not sure it would be wise to try to fix any existing configuration on plugin upgrade, but I could re-run the search for the executable in case of an error.

**Comment by Cypaubr** [comment]
I guess that's the probelm. I reproduced on another PC, same issue idem on Mac.

**Comment by SRombauts** [comment]
I have actually never been able to reprodude the issue, and it's not showing in my recent tests, so I am closing it
