### ISSUE TITLE
On Changeset List for Diffing Blueprints, all are dated "Dec 31, 1"

### ISSUE THREAD

**Issue by reveracorp** [SRombauts/UE4PlasticPlugin#75]
Hi,

Repro:
Open a blueprint,
Click on FIle,
hover over Diff,
and then hover any one of the changesets which populate.

On that hover, a small 'tooltip' pops up with the changeset numbers, decription and date.

The date is fixed for all at: 'Dec 31, 1'

Best,

**Comment by SRombauts** [comment]
Thanks for reporting this, I don't know when Plastic SCM changed the date format, but I now try to handle any
