### ISSUE TITLE
DiffAgainstDepot compares to the latest regardless of branch

### ISSUE THREAD

**Issue by Dzarg** [SRombauts/UE4PlasticPlugin#78]
Hi again :)

When using `DiffAgainstDepot` the plugin seems to compare my workspace file to the last checked in file regardless of what branch I'm in (and what the last checked in file is in). I would expect it to compare to the latest in the same branch as I am in. I'm using Plastic SCM 8.0.16.3868 and UE 4.24.2 at the moment.

Here's a piece of code found in `PerforceSourceControlOperations.cpp` function `ParseHistoryResults`
![image](https://user-images.githubusercontent.com/94673/82670762-6dae3a80-9c46-11ea-9ea6-91c02f80e553.png)

By quickly looking around I couldn't find similar code in the plastic plugin (though I haven't actually tried whether this works correctly with perforce either).

I'd assume this issue should be easy to reproduce. Is this a known issue? Or perhaps I have some configuration/version wrong that's causing this? Thanks in advance! :)

**Comment by SRombauts** [comment]
This actually looks like the exact opposite as #80 so I am kind of lost now....

**Comment by SRombauts** [comment]
I have finally fixed this, it's merged on master and will be released in the coming weeks
https://github.com/PlasticSCM/UE4PlasticPlugin/pull/25 Detect files changed on another branch
