### ISSUE TITLE
Every operation is extremely slow

### ISSUE THREAD

**Issue by Settius** [SRombauts/UE4PlasticPlugin#90]
Hello,

Every operation done from editor is extremely slow comparing to Plastic GUI. Renaming, moving but also checkouts takes almost a minute for single file. Unacceptable behavior when working for even medium size project but in case of large project slows down development immensely.

Thanks

**Comment by SRombauts** [comment]
Hello,

I am a bit late to the party, but can you give more details;
Are you using the latest version of the plugin I provide through this repository, or the older one provided by default in Unreal Engine?
There has been some fixes in here that wheren't integrated by Epic Games.

**Comment by Settius** [comment]
Hi,

I'm using branch of Unreal Engine 5.0 although https://github.com/EpicGames/UnrealEngine/tree/5.0/Engine/Plugins/Developer. Are you planning to make update for that engine version since already many teams are already using it?

Thanks

**Comment by SRombauts** [comment]
I am going to add better support for UE5 very soon, for sure! I did test it quickly on a template project a while ago and it seemed fine at this time so I didn't looked more into it.

Do you mean that the UE5 version is slower and or broken compared to the UE4 ones?

**Comment by SRombauts** [comment]
I need to investigate this "checkout takes one minute" it's crazy and I never experienced anything like that. 

Could you perhaps send me an extract of the logs with just this operation? Or a full quick session of the Editor if you don't mind (you can replace paths and names if you prefer)

**Comment by Settius** [comment]
In both UE4 and UE5 it was slow but in general when repo grows larger it slows down heavily.
On UE5 repo had additional 50GB so it was further slowed down.
It was extremely slow for repo with size around 300GB. Right now for fresh new repo (70GB) it's better but after few weeks it slows down while more content and changesets are committed. If you want to test and reproduce I suggest to prepare large repo.

**Comment by SRombauts** [comment]
I did some test a while ago and ago on my studio 100GB project without trouble so I guess it's not enough...

Perhaps is it related to having enough changesets
But perhaps it's related to the exact setup ; is the engine source and binaries all in the same repo with the game for instance?

**Comment by Settius** [comment]
Currently yes, but some time ago and in old repo we didn't have engine in the repo.
It could be related to number of changesets or it's combination of number of commits and repo size (number of files).

**Comment by SRombauts** [comment]
I will make more tests with bigger projects in the coming weeks, but in the short term can you send me some logs that might reveal something obviously wrong

And I'd love to get more info on your setup as well

**Comment by SRombauts** [comment]
And also, can you please tell me if it's a cloud instance or an on premise "Entreprise" plastic server ?

**Comment by Settius** [comment]
> And also, can you please tell me if it's a cloud instance or an on premise "Entreprise" plastic server ?

Standard cloud instance.

> I will make more tests with bigger projects in the coming weeks, but in the short term can you send me some logs that might reveal something obviously wrong

I don't have logs anymore but I've send them to plastic support.

Just some summary when renaming files in old repo:

I've check one file rename command times and move itself is very fast (0.125171s) comparing to reading commands:
- update status over 5s (16 times),
- fileinfo over 1s (12 times),
- add over 5s (2 times).

**Comment by SRombauts** [comment]
> I don't have logs anymore but I've send them to plastic support.
So do you mean that you don't have the problem currently?

> I've check one file rename command times and move itself is very fast (0.125171s) comparing to reading commands:
> 
> * update status over 5s (16 times),
> * fileinfo over 1s (12 times),
> * add over 5s (2 times).
Those are absolutely crazy numbers, I agree! 

I have been unable to reproduce anything like that with my first few tests using the cloud, but I am going to move on with bigger and bigger repositories!

**Comment by SRombauts** [comment]
Also to be totally honest, at this stage and given the above, I am not sure it can be caused by the plugin itself: to me it looks like "cm" times are very bad on themself

=> we could try to optimize Unreal to issue less "Update Status" operation (reduce the number of cm status & cm fileinfo) but this would just be a workround, it's not the root cause

**Comment by Settius** [comment]
>

**Comment by Settius** [comment]
> > I don't have logs anymore but I've send them to plastic support.
> > So do you mean that you don't have the problem currently?
> 
> > I've check one file rename command times and move itself is very fast (0.125171s) comparing to reading commands:
> > 
> > * update status over 5s (16 times),
> > * fileinfo over 1s (12 times),
> > * add over 5s (2 times).
> >   Those are absolutely crazy numbers, I agree!
> 
> I have been unable to reproduce anything like that with my first few tests using the cloud, but I am going to move on with bigger and bigger repositories!

That's the only way to reproduce. That's not the issue in small repo or with small amount of changesets.

**Comment by Settius** [comment]
> Also to be totally honest, at this stage and given the above, I am not sure it can be caused by the plugin itself: to me it looks like "cm" times are very bad on themself
> 
> => we could try to optimize Unreal to issue less "Update Status" operation (reduce the number of cm status & cm fileinfo) but this would just be a workround, it's not the root cause

I wouldn't call this workaround when overall times can be greatly reduced so much with less iterations but having faster times for those long operations might improve performance so much redundant updates wouldn't be an issues.

Doing the same operation without UE only with Plastic GUI was much faster. I don't know why but maybe it's using different events for updating status. Shouldn't it be even faster with UE when you can track every change directly and you don't have to check whole repo status?

**Comment by SRombauts** [comment]
Yes I agree, it should be much faster to update file status from within Unreal then from the GUI

**Comment by SRombauts** [comment]
But, do you mean that you don't have the problem anymore currently?

It would be worth to try to repro by executing the same commands from your windows terminal to compare, and also to add options to gather more infos

**Comment by Settius** [comment]
> But, do you mean that you don't have the problem anymore currently?
> 
> It would be worth to try to repro by executing the same commands from your windows terminal to compare, and also to add options to gather more infos

It's faster now since we were forced to create new repo. Previous repo was so slow we were wasting minutes for simple rename. What if I have dozens or hundreds of files to rename. Still it again became slower with each week.

You need to have large repo with many changesets. That's were it became extremely sluggish.

**Comment by SRombauts** [comment]
Could you run a console command similar to this one and post the result here please?

```
cm status --timer .\Content\Blueprints\
/main@UE4TestRepo@test@cloud (cs:5 - head)

391 ms
```

**Comment by SRombauts** [comment]
OK, that's interesting already, I'll forward to the core team and keep track of it. (and I am still uploading to my test cloud repo in the backgroud :)

part of the test is failing because it has to run from the workspace, but I see that you attempted to recover by giving a path

```
C:\Users\User>cm status --timer --nochanges
c:\Users\User is not in a workspace.
93 ms
```

**Comment by SRombauts** [comment]
```do they have a shared settings repo?```

check with **cm repo list** to see if you have one called **plastic-global-config** 

https://www.plasticscm.com/documentation/administration/plastic-scm-version-control-administrator-guide#Globalfileconfiguration
commands try to retrieve config files from the global one before running, so this adds delay to the operations… but it shouldn’t run before each and every one of them

**Comment by SRombauts** [comment]
I am sorry to ask more logs, and I know it's a bit of a pain to setup, but we will need the cm.log.txt corresponding to these tests
https://www.plasticscm.com/documentation/technical-articles/kb-enabling-logging-for-plastic-scm-part-i

**Comment by Settius** [comment]
Sorry but I don't have more time on that. I told what was my setup so you need to reproduce it and test first yourself. I'm not Plastic tester to waste time on that.

**Comment by SRombauts** [comment]
Yes, I understand you and I will do my best to reproduce. I'll keep you informed 

Though there is a chance that you triggered the problem by configuring the Shared GlobalConfig (previous message) Does it rings a bell?

**Comment by SRombauts** [comment]
Hello @Settius,

```
I'm using branch of Unreal Engine 5.0 although https://github.com/EpicGames/UnrealEngine/tree/5.0/Engine/Plugins/Developer. Are you planning to make update for that engine version since already many teams are already using it?
```

When you can, have a try at the latest version of the plugin https://github.com/SRombauts/UE4PlasticPlugin/releases/tag/1.4.11

It does compile now with UE5.
This is only the beginning, I'll add support for the One File Per Actor & the Changelists, including performance improvements that are required for this.

I wasn't ever able to reproduce your problem, however big the repository I created, even by adding artificial latencies.
But I did improve performances on all "status" commands so you should be in a better situation.

**Comment by Settius** [comment]
I've tested moving 500 files and it was slow but not terribly slow.
Checkout was slow compared to moving.

śr., 30 mar 2022 o 11:35 Sébastien Rombauts ***@***.***>
napisał(a):

**Comment by Settius** [comment]
Is it bug free? I'll keep testing but I don't want to commit to repo it
until it's finished.

**Comment by SRombauts** [comment]
Thanks for testing.
No it's not bug-free, it was just a first release, but I have a list of known issues.
There is at least one other performance fix in the pipe specifically for Unreal 5 so it should help further.
You can expect probably a release every week, or every two weeks. I'll keep you posted

**Comment by SRombauts** [comment]
I have now released two more versions of the plugin

- [1.4.12 focused on performances](https://github.com/SRombauts/UE4PlasticPlugin/releases/tag/1.4.12) 
- [1.4.13 focused on fixing remaining bugs and perfs](https://github.com/SRombauts/UE4PlasticPlugin/releases/tag/1.4.13) 

Let us know how it behaves, especially if you ever encounter abnormal command line timing (like +1s for a single command)!

**Comment by Settius** [comment]
Thanks,

I'll try to test this week, maybe next. Is it working well with 5.0.1?

Thanks,
Andrzej Zając


śr., 4 maj 2022 o 12:18 Sébastien Rombauts ***@***.***>
napisał(a):

**Comment by SRombauts** [comment]
Yes it is working well with UE5 as it is now my main development environment.
