### ISSUE TITLE
Human-friendly config for usernames shown for locked files

### ISSUE THREAD

**Issue by seesemichaelj** [SRombauts/UE4PlasticPlugin#99]
It would be great if there was a way where we could create a mapping for usernames so that the `Locked By` prompt shows the human friendly version instead of just the username. While this is a desirable feature for all source control providers, it definitely starts to become desired for Plastic Cloud repos where the usernames are the full email address.

For example I want to configure `mike@incanta.games` to display `Mike` and `sleepypanda@gmail.com` to be `Joe`

**Comment by SRombauts** [comment]
Thanks for the suggestion, this would indeed be very interesting for some team!

**Comment by SRombauts** [comment]
Hello, if you want to try, have a look at #101, it should do the trick :)

**Comment by seesemichaelj** [comment]
Heck yes! Thank you for such a swift response. I'll check out #101!
